// <auto-generated />
using System;
using Dershane.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dershane.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250429134352_Dershane1")]
    partial class Dershane1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dershane.Core.Models.Brans", b =>
                {
                    b.Property<int>("BransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BransId"));

                    b.Property<string>("BransAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BransId")
                        .HasName("PK__Brans__D0E572ECFBFEE107");

                    b.ToTable("Brans");
                });

            modelBuilder.Entity("Dershane.Core.Models.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersId"));

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DersUcret")
                        .HasColumnType("int");

                    b.Property<int>("OgretmenId")
                        .HasColumnType("int");

                    b.HasKey("DersId")
                        .HasName("PK__Ders__E8B3DE1188AED3FF");

                    b.ToTable("Ders");
                });

            modelBuilder.Entity("Dershane.Core.Models.DersSaat", b =>
                {
                    b.Property<int>("DersSaatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersSaatId"));

                    b.Property<DateOnly>("DersTarihi")
                        .HasColumnType("date");

                    b.Property<decimal>("GirilenSaat")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("OgretmenId")
                        .HasColumnType("int");

                    b.HasKey("DersSaatId")
                        .HasName("PK__DersSaat__C006BE39AEC44B16");

                    b.HasIndex("OgretmenId");

                    b.ToTable("DersSaat");
                });

            modelBuilder.Entity("Dershane.Core.Models.DersUcret", b =>
                {
                    b.Property<int>("DersUcretId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersUcretId"));

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("OgretmenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SaatlikUcret")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.HasKey("DersUcretId")
                        .HasName("PK__DersUcre__5A0EA069057A8248");

                    b.HasIndex("DersId");

                    b.HasIndex("OgretmenId");

                    b.HasIndex("SinifId");

                    b.ToTable("DersUcret");
                });

            modelBuilder.Entity("Dershane.Core.Models.Kullanici", b =>
                {
                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("Brans")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CepTel")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("EPosta")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Parola")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("PersonelNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("KullaniciId")
                        .HasName("PK__Kullanic__E011F77B192904DC");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("Dershane.Core.Models.KullaniciRol", b =>
                {
                    b.Property<int>("KullaniciRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciRolId"));

                    b.Property<Guid>("KayitKullaniciId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KullaniciRolId")
                        .HasName("PK__Kullanic__F316ADA92FA37CC6");

                    b.ToTable("KullaniciRol");
                });

            modelBuilder.Entity("Dershane.Core.Models.MuhasebeKayitlari", b =>
                {
                    b.Property<int>("KayitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KayitId"));

                    b.Property<int>("DonemAy")
                        .HasColumnType("int");

                    b.Property<int>("DonemYil")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HesaplananTarih")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("OgretmenId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamSaat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("KayitId")
                        .HasName("PK__Muhasebe__BD28AF4BC6DA0638");

                    b.HasIndex("OgretmenId");

                    b.ToTable("MuhasebeKayitlari");
                });

            modelBuilder.Entity("Dershane.Core.Models.Odeme", b =>
                {
                    b.Property<int>("OdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdemeId"));

                    b.Property<string>("OdemeTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("Oran")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.HasKey("OdemeId")
                        .HasName("PK__Odeme__B11B668D758C8599");

                    b.ToTable("Odeme");
                });

            modelBuilder.Entity("Dershane.Core.Models.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciId"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<string>("OgrenciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OgrenciSoyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OgrenciTc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OgrenciTel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("VeliId")
                        .HasColumnType("int");

                    b.HasKey("OgrenciId")
                        .HasName("PK__Ogrenci__E497E6B4D27CC5EA");

                    b.ToTable("Ogrenci");
                });

            modelBuilder.Entity("Dershane.Core.Models.OgrenciDers", b =>
                {
                    b.Property<int>("OgrenciDersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciDersId"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("BaslangicTarihi")
                        .HasColumnType("date");

                    b.Property<DateOnly>("BitisTarihi")
                        .HasColumnType("date");

                    b.Property<int>("GirilecekDersSaati")
                        .HasColumnType("int");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<bool>("OgrenciIptali")
                        .HasColumnType("bit");

                    b.Property<int>("OgretmenId")
                        .HasColumnType("int");

                    b.Property<string>("OgretmenNotu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.HasKey("OgrenciDersId")
                        .HasName("PK__OgrenciD__C6ECD76C8B2EECB7");

                    b.HasIndex("OgrenciId");

                    b.HasIndex("OgretmenId");

                    b.HasIndex("SinifId");

                    b.ToTable("OgrenciDers");
                });

            modelBuilder.Entity("Dershane.Core.Models.Ogretmen", b =>
                {
                    b.Property<int>("OgretmenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgretmenId"));

                    b.Property<int>("BransId")
                        .HasColumnType("int");

                    b.Property<string>("OgretmenAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OgretmenDuzey")
                        .HasColumnType("int");

                    b.Property<string>("OgretmenMail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OgretmenSoyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OgretmenTc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.HasKey("OgretmenId")
                        .HasName("PK__Ogretmen__27A3276F2C84493D");

                    b.ToTable("Ogretmen");
                });

            modelBuilder.Entity("Dershane.Core.Models.OgretmenDersSaatleri", b =>
                {
                    b.Property<int>("KayitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KayitId"));

                    b.Property<int?>("DersId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DersTarihi")
                        .HasColumnType("date");

                    b.Property<int?>("OgretmenId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaatlikUcret")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("SinifId")
                        .HasColumnType("int");

                    b.Property<decimal>("ToplamSaat")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("ToplamTutar")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(21, 4)")
                        .HasComputedColumnSql("(CONVERT([decimal](10,2),[ToplamSaat])*CONVERT([decimal](10,2),[SaatlikUcret]))", true);

                    b.HasKey("KayitId")
                        .HasName("PK__Ogretmen__BD28AF4B7F7DE2B6");

                    b.HasIndex("DersId");

                    b.HasIndex("OgretmenId");

                    b.HasIndex("SinifId");

                    b.ToTable("OgretmenDersSaatleri");
                });

            modelBuilder.Entity("Dershane.Core.Models.OgretmenSinif", b =>
                {
                    b.Property<int>("OgretmenSinifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgretmenSinifId"));

                    b.Property<int>("OgretmenId")
                        .HasColumnType("int");

                    b.Property<int>("SinifId")
                        .HasColumnType("int");

                    b.Property<decimal>("Ucret")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OgretmenSinifId")
                        .HasName("PK__Ogretmen__29763B127EEEEEB8");

                    b.ToTable("OgretmenSinif");
                });

            modelBuilder.Entity("Dershane.Core.Models.Rol", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RolNo")
                        .HasColumnType("int");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RolId")
                        .HasName("PK__Rol__F92302F1ACA95878");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Dershane.Core.Models.Sinif", b =>
                {
                    b.Property<int>("SinifId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinifId"));

                    b.Property<string>("SinifSeviyesi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SinifId")
                        .HasName("PK__Sinif__5D59A88BDC0BA52C");

                    b.ToTable("Sinif");
                });

            modelBuilder.Entity("Dershane.Core.Models.Takvim", b =>
                {
                    b.Property<int>("TakvimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TakvimId"));

                    b.Property<int>("DersSaatId")
                        .HasColumnType("int");

                    b.Property<int>("OgretmenId")
                        .HasColumnType("int");

                    b.HasKey("TakvimId")
                        .HasName("PK__Takvim__A2EB925695374EE8");

                    b.ToTable("Takvim");
                });

            modelBuilder.Entity("Dershane.Core.Models.Veli", b =>
                {
                    b.Property<int>("VeliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VeliId"));

                    b.Property<string>("VeliAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VeliMail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VeliSoyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VeliTc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("VeliTel")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VeliId")
                        .HasName("PK__Veli__21C446257CF85D59");

                    b.ToTable("Veli");
                });

            modelBuilder.Entity("Dershane.Core.Models.DersSaat", b =>
                {
                    b.HasOne("Dershane.Core.Models.Ogretmen", "Ogretmen")
                        .WithMany("DersSaat")
                        .HasForeignKey("OgretmenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__DersSaat__Ogretm__571DF1D5");

                    b.Navigation("Ogretmen");
                });

            modelBuilder.Entity("Dershane.Core.Models.DersUcret", b =>
                {
                    b.HasOne("Dershane.Core.Models.Ders", "Ders")
                        .WithMany("DersUcretNavigation")
                        .HasForeignKey("DersId")
                        .IsRequired()
                        .HasConstraintName("FK_DersUcret_Ders");

                    b.HasOne("Dershane.Core.Models.Ogretmen", "Ogretmen")
                        .WithMany("DersUcret")
                        .HasForeignKey("OgretmenId")
                        .IsRequired()
                        .HasConstraintName("FK_DersUcret_Ogretmen");

                    b.HasOne("Dershane.Core.Models.Sinif", "Sinif")
                        .WithMany("DersUcret")
                        .HasForeignKey("SinifId")
                        .IsRequired()
                        .HasConstraintName("FK_DersUcret_Sinif");

                    b.Navigation("Ders");

                    b.Navigation("Ogretmen");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("Dershane.Core.Models.MuhasebeKayitlari", b =>
                {
                    b.HasOne("Dershane.Core.Models.Ogretmen", "Ogretmen")
                        .WithMany("MuhasebeKayitlari")
                        .HasForeignKey("OgretmenId")
                        .HasConstraintName("FK__MuhasebeK__Ogret__656C112C");

                    b.Navigation("Ogretmen");
                });

            modelBuilder.Entity("Dershane.Core.Models.OgrenciDers", b =>
                {
                    b.HasOne("Dershane.Core.Models.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDers")
                        .HasForeignKey("OgrenciId")
                        .IsRequired()
                        .HasConstraintName("FK_OgrenciDers_Ogrenci");

                    b.HasOne("Dershane.Core.Models.Ogretmen", "Ogretmen")
                        .WithMany("OgrenciDers")
                        .HasForeignKey("OgretmenId")
                        .IsRequired()
                        .HasConstraintName("FK_OgrenciDers_Ogretmen");

                    b.HasOne("Dershane.Core.Models.Sinif", "Sinif")
                        .WithMany("OgrenciDers")
                        .HasForeignKey("SinifId")
                        .IsRequired()
                        .HasConstraintName("FK_OgrenciDers_Sinif");

                    b.Navigation("Ogrenci");

                    b.Navigation("Ogretmen");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("Dershane.Core.Models.OgretmenDersSaatleri", b =>
                {
                    b.HasOne("Dershane.Core.Models.Ders", "Ders")
                        .WithMany("OgretmenDersSaatleri")
                        .HasForeignKey("DersId")
                        .HasConstraintName("FK__OgretmenD__DersI__628FA481");

                    b.HasOne("Dershane.Core.Models.Ogretmen", "Ogretmen")
                        .WithMany("OgretmenDersSaatleri")
                        .HasForeignKey("OgretmenId")
                        .HasConstraintName("FK__OgretmenD__Ogret__60A75C0F");

                    b.HasOne("Dershane.Core.Models.Sinif", "Sinif")
                        .WithMany("OgretmenDersSaatleri")
                        .HasForeignKey("SinifId")
                        .HasConstraintName("FK__OgretmenD__Sinif__619B8048");

                    b.Navigation("Ders");

                    b.Navigation("Ogretmen");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("Dershane.Core.Models.Ders", b =>
                {
                    b.Navigation("DersUcretNavigation");

                    b.Navigation("OgretmenDersSaatleri");
                });

            modelBuilder.Entity("Dershane.Core.Models.Ogrenci", b =>
                {
                    b.Navigation("OgrenciDers");
                });

            modelBuilder.Entity("Dershane.Core.Models.Ogretmen", b =>
                {
                    b.Navigation("DersSaat");

                    b.Navigation("DersUcret");

                    b.Navigation("MuhasebeKayitlari");

                    b.Navigation("OgrenciDers");

                    b.Navigation("OgretmenDersSaatleri");
                });

            modelBuilder.Entity("Dershane.Core.Models.Sinif", b =>
                {
                    b.Navigation("DersUcret");

                    b.Navigation("OgrenciDers");

                    b.Navigation("OgretmenDersSaatleri");
                });
#pragma warning restore 612, 618
        }
    }
}
